url: "https://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-LouisTacheron" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  films:
    output: true

plugins:
  - jekyll-admin
