url: "https://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-LouisTacheron" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  films:
    output: true

  series:
    output: true

  cameras:
    output: true

  realisateurs:
    output: true

plugins:
  - jekyll-admin

nav_links:
  - name: Top 4 des meilleurs films
    link: films.html
    cover_image: assets/img/dunkerk.jpg
  - name: Top 4 des meilleurs cameras
    link: cameras.html
    cover_image: assets/img/arri-alexa.jpg
  - name: Top 4 des meilleurs séries
    link: series.html
    cover_image: assets/img/maniac.jpg
  - name: Top 4 des meilleurs réalisateurs
    link: real.html
    cover_image: assets/img/del-torro.jpg
